Repository codesquad-members-2024/git-sandbox, pull requests merged in 2024-03, with the labels that each got.

#2 [호눅스] 1-1 완료
  hello.txt
Labels: crong-bad

#3 스텝 1-2
  hello.txt
Labels: step-1-1

#8 1
  .idea/.gitignore
  .idea/encodings.xml
  .idea/git-sandbox.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  One.java
Labels: step-1-1

#9 test
  Test.java
Labels: good first issue

#10 test2
  Test.java
  Test2.java
Labels: enhancement
